# Generated by Django 3.2.8 on 2021-10-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='test',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
