# Generated by Django 3.2.8 on 2021-10-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='test',
        ),
    ]
